"""Project-wide constants for muscle-driven arm control."""

from typing import Final

# --- Simulation ---
DEFAULT_TIMESTEP: Final = 0.01  # seconds
DEFAULT_MAX_EPISODE_TIME: Final = 3.0  # seconds
DEFAULT_MAX_EPISODE_STEPS: Final = 300
OBS_CLIP_MIN: Final = -10.0
OBS_CLIP_MAX: Final = 10.0

# --- Environment ---
DEFAULT_PRE_DELAY_RANGE: Final = (0.2, 0.5)
DEFAULT_HOLD_DURATION_RANGE: Final = (0.3, 0.8)
DEFAULT_POST_DELAY_RANGE: Final = (0.1, 0.3)
DEFAULT_REACH_THRESHOLD: Final = 0.05
DEFAULT_HOLD_REWARD_WEIGHT: Final = 1.0
DEFAULT_ENERGY_PENALTY_WEIGHT: Final = 0.01
DEFAULT_RIDGE_PENALTY_WEIGHT: Final = 1e-3
DEFAULT_LASSO_PENALTY_WEIGHT: Final = 0.0
DEFAULT_REACH_BONUS: Final = 0.5
DEFAULT_SUCCESS_REWARD: Final = 1.0

# --- Network Architecture ---
DEFAULT_NUM_MUSCLES: Final = 4
DEFAULT_RNN_HIDDEN_SIZE: Final = 32
DEFAULT_MLP_HIDDEN_SIZES: Final = (256, 256, 128)
DEFAULT_NUM_TARGET_UNITS: Final = 16  # target_grid_size^2
DEFAULT_TARGET_GRID_SIZE: Final = 4
DEFAULT_TARGET_GRID_PADDING: Final = 0.5  # fraction of workspace size
DEFAULT_TARGET_SIGMA: Final = 0.5

# --- CMA-ES Training ---
DEFAULT_POPULATION_SIZE: Final = 32
DEFAULT_NUM_GENERATIONS: Final = 1000
DEFAULT_CMAES_SIGMA: Final = 0.25
DEFAULT_NUM_EVAL_EPISODES: Final = 5
DEFAULT_TARGET_FITNESS: Final = 50.0
DEFAULT_PATIENCE: Final = 250
DEFAULT_CHECKPOINT_EVERY: Final = 100
DEFAULT_INSPECTION_EVERY: Final = 25

# --- Distillation Training ---
DEFAULT_TEACHER_LR: Final = 1e-3
DEFAULT_TEACHER_EPOCHS: Final = 100
DEFAULT_TEACHER_BATCH_SIZE: Final = 64
DEFAULT_TEACHER_DATA_EPISODES: Final = 1000
DEFAULT_STUDENT_LR: Final = 1e-4
DEFAULT_STUDENT_EPOCHS: Final = 200
DEFAULT_STUDENT_BATCH_SIZE: Final = 32
DEFAULT_STUDENT_SEQ_LEN: Final = 50
DEFAULT_ACTION_LOSS_WEIGHT: Final = 1.0

# --- Calibration ---
DEFAULT_CALIBRATION_EPISODES: Final = 100
DEFAULT_CALIBRATION_STEPS: Final = 200
DEFAULT_WORKSPACE_SAMPLES: Final = 1000

# --- Visualization ---
DEFAULT_RENDER_MODE: Final = "human"
DEFAULT_VIDEO_FPS: Final = 60
DEFAULT_DPI: Final = 100
DEFAULT_PLOT_DPI: Final = 150
DEFAULT_SHOW_RNN_UNITS: Final = 32  # Number of RNN units to display in visualizer
