_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.11.12
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 35
                - 55
            "4": 3.11.12
            "5": 0.19.11
            "8":
                - 5
            "9":
                "2": tianshou
            "12": 0.19.11
            "13": linux-x86_64
batch_size:
    value: 64
buffer_size:
    value: 2048
epoch:
    value: 15
hidden_size:
    value: 128
lr:
    value: 0.0003
num_layers:
    value: 1
repeat_per_collect:
    value: 4
step_per_collect:
    value: 1000
step_per_epoch:
    value: 10000
tau_mem:
    value: 20
